name: miyazaki_transport_app
description: A new Flutter project.
publishTo: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/bus_stops/miyazaki_bus_stops.json
